### ISSUE TITLE
Markov Text Generator First Load

### ISSUE THREAD

**Issue by supershdow** [sonar235/webOne#3]
The first time you load the markov text generator, it does not give you options for picking a book.
Also, Caesar is not spelled Ceasar

**Comment by sonar235** [comment]
Haha, thanks for the spellcheck. We'll try to solve that issue!

**Comment by sonar235** [comment]
Resolved. Thanks for your input! <3

**Comment by sonar235** [comment]
Resolved. Thanks for your input! <3
